
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_admin?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

#mybatis:
#    configuration:
#    map-underscore-to-camel-case: true

server:
  port: 8081

logging:
  level:
    root: info
    com.chinasoft: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  configuration:
    map-underscore-to-camel-case: true



